#!/usr/bin/env python3
"""Generate OPTIONS reports for all portfolio holdings inline."""

import os

TS = "20260915-1307"
RUN_ID = "options-20260915-1307-59b4c3"
DATE = "2026-09-15T13:07:00-04:00"

# ── REPORT TEMPLATES ──────────────────────────────────────────────────────────

REPORTS = {}

# ─── CLOV: LONG + BUY + High IV → PMCC (< 100 shares) ────────────────────────
REPORTS["CLOV"] = f"""---
trade_report: true
schema_version: 1
ticker: CLOV
company: Clover Health Investments, Inc.
report_type: OPTIONS
generated_at: {DATE}
signal: BUY
price_at_analysis: 5.10
iv_rank: 62
strategy_outlook: INCOME
recommended_strategy: Poor Man's Covered Call (PMCC)
position_bias: LONG
run_id: {RUN_ID}
---

# Options Analysis: CLOV — Clover Health Investments, Inc.

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$5.10 | **Market Cap:** ~$580M
**Next Earnings:** ~Q4 2026
**Your Position:** LONG ~37 shares (< 100 shares; covered call unavailable — PMCC recommended)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~82% | Stock expected to move ~24% per month (annualized) |
| IV Rank (52-week) | ~62% | Current IV higher than ~62% of the past year |
| IV Percentile | ~60% | Elevated volatility environment |
| 30-Day HV | ~70% | IV slightly above recent realized vol |
| IV/HV Ratio | ~1.17 | Options modestly expensive vs recent history |
| IV Skew | Elevated | Puts priced at premium; bearish hedging demand evident |

**IV Environment: HIGH**
**Strategy Bias: Sell Premium (INCOME)**

CLOV carries structurally elevated IV as a small-cap managed-care insurer with ongoing profitability questions. IV rank ~62% confirms options are pricing above-average fear. With a BUY signal (composite 72/A) and high IV, income generation via a PMCC is optimal — the elevated premium finances the long leg and the BUY signal supports the bullish synthetic exposure.

---

## Strategy 1: Poor Man's Covered Call (PMCC) — RECOMMENDED

**Setup:**
- **Outlook:** Moderately bullish — BUY signal, composite 72/A, price ~$5.10
- **Why PMCC:** Only ~37 shares; covered call requires 100. PMCC substitutes with a deep-ITM long-dated call and a near-term short OTM call.

**Trade Details (indicative — verify live chain):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Long anchor | Buy | $3 (deep ITM, ~80Δ) | Jan 2027 | Call | ~$2.30 |
| Short income | Sell | $6 (OTM, ~30Δ) | Oct 2026 | Call | ~$0.40 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Net Debit | ~$1.90/share ($190/contract) |
| Max Profit | ~$1.10/contract (if CLOV reaches $6 at Oct expiry) |
| Max Loss | Net debit $190 (if CLOV collapses to zero) |
| Breakeven | ~$4.90 at front-month expiry |
| Theta Impact | Short call positive theta works for you |

**Management:**
- Roll the short call monthly for income (~$0.35–0.45/month target)
- If CLOV surpasses $6, roll short call up/out
- Close or roll long anchor when < 90 DTE

---

## Strategy 2: Long Call Debit Spread (Alternate — Bullish)

| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Buy | Long | $5 (ATM) | Nov 2026 | Call | ~$0.55 |
| Sell | Short | $7 (OTM) | Nov 2026 | Call | ~$0.15 |

Net debit ~$0.40 ($40/contract). Max profit $1.60 if CLOV reaches $7. Lower capital at risk than PMCC but also less income generation.

---

## Key Levels
| Level | Price | Significance |
|-------|-------|-------------|
| 52-week Low | ~$3.50 | Key downside reference |
| Current | $5.10 | Baseline |
| Short-call target | $6.00 | PMCC short strike |
| 52-week High | ~$7.00 | Upside resistance |

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── MARA: LONG + NEUTRAL + Very High IV → PMCC (< 100 shares) ───────────────
REPORTS["MARA"] = f"""---
trade_report: true
schema_version: 1
ticker: MARA
company: MARA Holdings Inc.
report_type: OPTIONS
generated_at: {DATE}
signal: NEUTRAL
price_at_analysis: 12.00
iv_rank: 58
strategy_outlook: INCOME
recommended_strategy: Poor Man's Covered Call (PMCC)
position_bias: LONG
nearest_catalyst_date: 2026-11-02
run_id: {RUN_ID}
---

# Options Analysis: MARA — MARA Holdings Inc.

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$12.00 | **Market Cap:** ~$3.5B
**Next Earnings:** ~2026-11-02 (~48 days)
**Your Position:** LONG ~37 shares (< 100 shares; covered call unavailable — PMCC recommended)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~105% | Crypto miner — extremely high vol; large monthly expected moves |
| IV Rank (52-week) | ~58% | Moderately elevated vs its own history |
| IV Percentile | ~55% | Above-average IV environment for MARA |
| 30-Day HV | ~90% | IV at premium to recent realized vol |
| IV/HV Ratio | ~1.17 | Options slightly expensive |
| IV Skew | Elevated | Calls and puts both priced up; event-driven premium |

**IV Environment: VERY HIGH**
**Strategy Bias: Sell Premium (INCOME)**

MARA's IV is structurally elevated due to its Bitcoin correlation (~0.85) and the additional operational/mining leverage. With a NEUTRAL signal (composite 47/C) and very high IV, the primary goal is harvesting that premium. With only ~37 shares, a PMCC (deep-ITM long call + short OTM call) is the covered-call substitute. Avoid naked short positions given asymmetric upside if BTC rallies.

---

## Strategy 1: Poor Man's Covered Call (PMCC) — RECOMMENDED

**Setup:**
- **Outlook:** Neutral-to-slight bullish range (~$10–$15 expected range near term)
- **Why PMCC:** ~37 shares, high IV makes the long anchor affordable and the short call premium generous

**Trade Details (indicative):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Long anchor | Buy | $8 (deep ITM, ~80Δ) | Jan 2027 | Call | ~$4.80 |
| Short income | Sell | $14 (OTM, ~30Δ) | Oct 2026 | Call | ~$0.90 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Net Debit | ~$3.90/share ($390/contract) |
| Monthly income target | ~$0.75–0.90/month from short call rolls |
| Max Loss | Net debit if MARA collapses |
| Key risk | Earnings (Nov 2) — consider closing or rolling short call before earnings |

**Earnings Alert (Nov 2):** Close the short call 5–7 days before earnings to avoid IV crush on the short leg or a gap-up through the short strike. Re-open after earnings settle.

---

## Strategy 2: Bull Call Spread (Alternate — for BTC rally scenario)

| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Buy | Long | $12 (ATM) | Nov 2026 | Call | ~$1.80 |
| Sell | Short | $17 (OTM) | Nov 2026 | Call | ~$0.70 |

Net debit ~$1.10 ($110/contract). Max profit $3.90 if MARA reaches $17. Lower capital, defined risk.

---

## Key Levels
| Level | Price | Significance |
|-------|-------|-------------|
| Stop-loss | $10.00 | Prior support |
| Current | $12.00 | Baseline |
| Short-call target | $14.00 | PMCC short strike |
| Resistance | $16–$18 | Prior highs |

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── NIO: LONG + CAUTION + High IV → Protective Put (333 shares = 3 contracts) ─
REPORTS["NIO"] = f"""---
trade_report: true
schema_version: 1
ticker: NIO
company: NIO Inc.
report_type: OPTIONS
generated_at: {DATE}
signal: CAUTION
price_at_analysis: 3.69
iv_rank: 68
strategy_outlook: HEDGE
recommended_strategy: Protective Put
position_bias: LONG
nearest_catalyst_date: 2026-10-07
run_id: {RUN_ID}
---

# Options Analysis: NIO — NIO Inc. (Chinese EV)

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$3.69 | **Market Cap:** ~$7.6B (ADR)
**Next Catalyst:** ~2026-10-07 (earnings/delivery data)
**Your Position:** LONG ~333 shares (~3 contracts available)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~78% | Chinese ADR with geopolitical/macro risk; high vol |
| IV Rank (52-week) | ~68% | Elevated — near the top of the past year's IV range |
| IV Percentile | ~65% | Above-average IV; protective put costs elevated |
| 30-Day HV | ~65% | IV running at modest premium to realized vol |
| IV/HV Ratio | ~1.20 | Options moderately expensive |
| IV Skew | Pronounced | Puts significantly more expensive than calls; heavy hedging demand |

**IV Environment: HIGH**
**Strategy Bias: HEDGE — CAUTION signal mandates downside protection**

NIO has a CAUTION signal (composite 39/D, CAUTION) driven by weak technical score (30/100), low overall conviction, and China macro headwinds. The position is -41.7% from cost. With high IV and a CAUTION signal, the skill matrix clearly calls for a Protective Put or Collar. Given the high put premium (IV rank 68%), a costless or near-costless collar is explored as an alternative. However, with the stock already deeply underwater, a protective put establishes a floor without capping further recovery.

---

## Strategy 1: Protective Put — RECOMMENDED (Hedge)

**Setup:**
- **Outlook:** CAUTION — protect against further decline while maintaining upside if NIO recovers
- **Position:** ~333 shares → buy 3 put contracts (1 per 100 shares)

**Trade Details (indicative):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Protection | Buy | $3.50 (near-ATM) | Dec 2026 | Put | ~$0.55 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Cost | ~$0.55 × 3 contracts = ~$165 total premium |
| Protection level | $3.50 (floor for your 333 shares) |
| Max Loss below floor | $0 (capped at strike - current price delta, minus premium) |
| Premium as % of position | ~$165 / $1,228 ≈ 13.4% (expensive; reflects high IV) |
| Expiration | Dec 2026 (protects through next earnings cycle) |

**Alternative — Costless Collar:**
Sell a $4.50 Oct 2026 call (~$0.25) to partially offset put cost. Limits upside to $4.50 but reduces net cost.

**Management:**
- If NIO drops below $3.50, puts gain — consider exercising or selling to lock in protection
- If NIO recovers above $4.50 and you have a collar, roll the short call up/out

---

## Key Levels
| Level | Price | Significance |
|-------|-------|-------------|
| Stop-loss | $3.25 | Prior analysis stop |
| Current | $3.69 | Baseline |
| Put floor | $3.50 | Protective put strike |
| Target (recovery) | $4.50+ | Collar short-call target if used |
| Next catalyst | ~Oct 7 | Delivery data — binary risk |

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── SPCE: LONG + AVOID + Very High IV → Protective Put (50 shares) ──────────
REPORTS["SPCE"] = f"""---
trade_report: true
schema_version: 1
ticker: SPCE
company: Virgin Galactic Holdings (restructured)
report_type: OPTIONS
generated_at: {DATE}
signal: AVOID
price_at_analysis: 3.01
iv_rank: 72
strategy_outlook: HEDGE
recommended_strategy: Protective Put
position_bias: LONG
nearest_catalyst_date: 2026-11-12
run_id: {RUN_ID}
---

# Options Analysis: SPCE — Virgin Galactic Holdings

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$3.01 | **Market Cap:** Micro-cap / distressed
**Next Catalyst:** ~2026-11-12 (earnings)
**Your Position:** LONG ~50 shares (< 100 shares — no covered call; 1 put contract over-protects slightly)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~120%+ | Distressed small-cap; options pricing extreme downside |
| IV Rank (52-week) | ~72% | Near the top of the year's IV range |
| IV Percentile | ~70% | Very elevated |
| 30-Day HV | ~100% | Realized vol also very high |
| IV/HV Ratio | ~1.20 | Options moderately expensive even vs realized vol |
| Liquidity | LIMITED | Wide bid-ask spreads expected; check chain liquidity |

**IV Environment: VERY HIGH — Distressed Name**
**Strategy Bias: HEDGE — AVOID signal; downside protection is imperative**

SPCE carries an AVOID signal (composite 20/F), reflecting fundamental viability concerns, deteriorating balance sheet, and continued operational losses. With -74.9% loss from cost and an AVOID signal, the only rational options posture is downside protection. Note: at $3.01/share and very high IV, put premiums will be expensive. Evaluate whether the insurance cost is justified relative to position size ($149.50 market value).

**⚠️ Liquidity Warning:** At ~$3 and micro-cap status, SPCE options may have very wide spreads or limited open interest. Verify the chain is tradeable before placing orders.

---

## Strategy 1: Protective Put — RECOMMENDED

**Setup:**
- **Outlook:** AVOID — limit catastrophic loss on a distressed holding
- **Position:** ~50 shares → buy 1 put contract (protects 100 shares; slight over-protection but 1 is the minimum)

**Trade Details (indicative — chain liquidity must be verified):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Protection | Buy | $2.50 (OTM) | Nov 2026 | Put | ~$0.60–0.90 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Cost | ~$70–90 per contract (covers 100 shares vs your 50) |
| Protection level | $2.50 floor |
| Position value | ~$150 (50 shares × $3.01) |
| Premium as % of position | ~47–60% — very expensive due to distress |
| Recommendation note | Consider whether protection cost outweighs position value |

**⚠️ Cost-Benefit Warning:** At $150 market value, a $70–90 put may not be economically rational. An alternative: accept the full downside risk given the small position size and maintain a mental stop at $2.55.

---

## Alternative: Sell (Exit) vs Hedge

Given the AVOID signal and -74.9% position, the most rational action may be to **exit SPCE entirely** (harvest the remaining $150 for redeployment) rather than paying for expensive put protection. This is not financial advice — consult your advisor on tax-loss harvesting implications.

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── ZAG: Canadian ETF — no US options ────────────────────────────────────────
REPORTS["ZAG"] = f"""---
trade_report: true
schema_version: 1
ticker: ZAG
company: BMO Aggregate Bond Index ETF
report_type: OPTIONS
generated_at: {DATE}
signal: NEUTRAL
price_at_analysis: 13.35
strategy_outlook: NEUTRAL
recommended_strategy: No Options Available (Canadian ETF)
position_bias: LONG
run_id: {RUN_ID}
---

# Options Analysis: ZAG — BMO Aggregate Bond Index ETF

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$13.35 CAD | **Listed:** TSX (Canadian ETF)
**Your Position:** LONG ~51 units

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Options Availability

**ZAG is a Canadian-listed ETF (Toronto Stock Exchange).** It does not have a liquid US-listed options chain. Canadian-listed ETFs generally do not have standardized exchange-traded options available through US retail brokers.

**Options verdict: NOT AVAILABLE for standard retail options strategies.**

### Signal Context
- **Signal:** NEUTRAL (composite 41/C)
- **Position:** LONG ~51 units
- **Recommendation:** Hold per signal. No options overlay applicable.

### Alternatives (if hedging is desired)
For interest-rate / bond exposure hedging, consider:
- **TLT options** (iShares 20+ Year Treasury Bond ETF — US-listed, highly liquid) as a proxy hedge
- **HYG or LQD put spreads** as broader fixed income hedges

No action is required for ZAG at this time given the NEUTRAL signal and low-IV nature of bond ETFs.

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── XEQT: Canadian ETF — no US options ───────────────────────────────────────
REPORTS["XEQT"] = f"""---
trade_report: true
schema_version: 1
ticker: XEQT
company: iShares Core Equity ETF Portfolio
report_type: OPTIONS
generated_at: {DATE}
signal: HOLD
price_at_analysis: 44.98
strategy_outlook: NEUTRAL
recommended_strategy: No Options Available (Canadian ETF)
position_bias: LONG
nearest_catalyst_date: 2026-09-17
run_id: {RUN_ID}
---

# Options Analysis: XEQT — iShares Core Equity ETF Portfolio

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$44.98 CAD | **Listed:** TSX (Canadian ETF)
**Your Position:** LONG ~46 units (combined TFSA + Moomoo TFSA)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Options Availability

**XEQT is a Canadian-listed ETF (Toronto Stock Exchange).** It does not trade on US exchanges and does not have a standardized options chain available through US retail brokers.

**Options verdict: NOT AVAILABLE for standard retail options strategies.**

### Signal Context
- **Signal:** HOLD (composite 63/B)
- **Position:** LONG ~46 units
- **Recommendation:** No options overlay applicable. HOLD — maintain position per signal.

### Alternatives (if hedging desired)
XEQT is a global all-in-one equity ETF. For a broad equity hedge:
- **SPY puts** or **QQQ puts** as a partial proxy for the global equity component
- **XIU options** (iShares S&P/TSX 60 ETF — Canadian listed, may have some options liquidity) for the Canadian equity component

No options action is required for XEQT at this time.

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── IBIT: LONG + NEUTRAL + High IV → PMCC (< 100 shares) ────────────────────
REPORTS["IBIT"] = f"""---
trade_report: true
schema_version: 1
ticker: IBIT
company: iShares Bitcoin Trust ETF
report_type: OPTIONS
generated_at: {DATE}
signal: NEUTRAL
price_at_analysis: 44.43
iv_rank: 52
strategy_outlook: INCOME
recommended_strategy: Poor Man's Covered Call (PMCC)
position_bias: LONG
nearest_catalyst_date: 2026-09-17
run_id: {RUN_ID}
---

# Options Analysis: IBIT — iShares Bitcoin Trust ETF

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$44.43 | **Market Cap:** Bitcoin-linked
**Next Catalyst:** ~2026-09-17 (Fed meeting / Bitcoin catalyst)
**Your Position:** LONG ~33 shares combined (TFSA + RRSP) — < 100 shares; PMCC recommended

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~62% | Bitcoin ETF; structurally elevated vol |
| IV Rank (52-week) | ~52% | Moderate — near median of past year's range |
| IV Percentile | ~50% | Neutral IV environment |
| 30-Day HV | ~55% | IV running modest premium to realized |
| IV/HV Ratio | ~1.13 | Options slightly rich |
| IV Skew | Moderate | Puts slightly more expensive; modest hedging demand |

**IV Environment: MODERATE-HIGH**
**Strategy Bias: Sell Premium (INCOME)**

IBIT's IV is structurally elevated due to Bitcoin's underlying volatility. With a NEUTRAL signal (composite 49/C) and IV rank ~52%, selling premium via a PMCC is appropriate. The ~33 combined shares (TFSA + RRSP) fall below 100, so a standard covered call is unavailable. The PMCC uses a deep-ITM long call anchor with a near-term short OTM call to generate monthly income.

**Note:** IBIT is held across two accounts (TFSA and RRSP). Options would need to be executed in a margin/non-registered account if your broker restricts options in registered accounts.

---

## Strategy 1: Poor Man's Covered Call (PMCC) — RECOMMENDED

**Trade Details (indicative):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Long anchor | Buy | $35 (deep ITM, ~80Δ) | Jan 2027 | Call | ~$10.50 |
| Short income | Sell | $50 (OTM, ~30Δ) | Oct 2026 | Call | ~$1.20 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Net Debit | ~$9.30/share ($930/contract) |
| Monthly income | ~$1.00–1.20/month from short call rolls |
| Max Profit | ~$5.70/contract if IBIT reaches $50 at Oct expiry |
| Breakeven | ~$44.30 at front-month expiry |

**Management:**
- Roll short call monthly; target ~$1.00 premium per roll
- If Bitcoin rallies sharply past $50, roll short call up/out
- Close if IBIT breaks below $40 (near-term support)

---

## Key Levels
| Level | Price | Significance |
|-------|-------|-------------|
| Support | $40.00 | Near-term support |
| Current | $44.43 | Baseline |
| Short-call target | $50.00 | PMCC short strike |
| Resistance | $52–$55 | Prior high zone |

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── VDY: Canadian ETF — no US options ────────────────────────────────────────
REPORTS["VDY"] = f"""---
trade_report: true
schema_version: 1
ticker: VDY
company: Vanguard FTSE Canadian High Dividend Yield Index ETF
report_type: OPTIONS
generated_at: {DATE}
signal: BUY
price_at_analysis: 76.80
strategy_outlook: NEUTRAL
recommended_strategy: No Options Available (Canadian ETF)
position_bias: LONG
nearest_catalyst_date: 2026-09-19
run_id: {RUN_ID}
---

# Options Analysis: VDY — Vanguard FTSE Canadian High Dividend Yield Index ETF

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$76.80 CAD | **Listed:** TSX (Canadian ETF)
**Your Position:** LONG ~18 units

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Options Availability

**VDY is a Canadian-listed ETF (Toronto Stock Exchange).** No standardized options chain is available through US retail brokers.

**Options verdict: NOT AVAILABLE for standard retail options strategies.**

### Signal Context
- **Signal:** BUY (composite 71/A)
- **Position:** LONG ~18 units
- **Recommendation:** No options overlay required or available. BUY signal supports holding and accumulating.

### Alternatives (if income generation desired)
VDY tracks Canadian high-dividend equities. For covered call income exposure in this space:
- **ZWC** (BMO Canadian High Dividend Covered Call ETF — Canadian listed) provides built-in CC income
- For US-proxy: **DVY** or **HDIV** in US markets may have options

VDY itself is a core long-term holding — BUY signal supports continuing to hold.

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── DIVO: LONG + HOLD + Low IV → Protective Put (<100 shares) ────────────────
REPORTS["DIVO"] = f"""---
trade_report: true
schema_version: 1
ticker: DIVO
company: Amplify CWP Enhanced Dividend Income ETF
report_type: OPTIONS
generated_at: {DATE}
signal: HOLD
price_at_analysis: 47.80
iv_rank: 35
strategy_outlook: HEDGE
recommended_strategy: Protective Put
position_bias: LONG
nearest_catalyst_date: 2026-09-26
run_id: {RUN_ID}
---

# Options Analysis: DIVO — Amplify CWP Enhanced Dividend Income ETF

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$47.80 | **Market Cap:** ~$3.8B ETF
**Your Position:** LONG ~48 shares (< 100 shares — collar unavailable; protective put recommended)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~18% | Dividend income ETF; low structural IV |
| IV Rank (52-week) | ~35% | Below-median IV; moderate IV environment |
| IV Percentile | ~33% | Low-to-moderate; protective puts are reasonably priced |
| 30-Day HV | ~14% | IV running at premium to realized vol |
| IV/HV Ratio | ~1.29 | Options slightly expensive vs recent history |
| IV Skew | Mild | Modest put premium; limited hedging demand |

**IV Environment: LOW-MODERATE**
**Strategy Bias: HEDGE (HOLD signal + low IV → Collar; with <100 shares → Protective Put)**

DIVO is an enhanced-dividend ETF that already employs a covered-call overlay internally — it is itself an income strategy. With a HOLD signal (composite 68/B) and low IV, the matrix calls for a Collar. However, with only ~48 shares, the covered-call leg requires 100 shares per contract. The fallback is a standalone protective put to establish a downside floor without requiring the short-call leg.

---

## Strategy 1: Protective Put — RECOMMENDED

**Setup:**
- **Outlook:** HOLD — maintain position with a floor below current price
- **Position:** ~48 shares → buy 1 put contract (covers 100 shares, slight over-protection)

**Trade Details (indicative):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Protection | Buy | $46 (slightly OTM) | Dec 2026 | Put | ~$1.50 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Cost | ~$1.50 × 1 contract = ~$150 |
| Protection level | $46.00 floor (protects 100 shares vs 48 owned) |
| Premium as % of position | ~$150 / $2,294 ≈ 6.5% (reasonable) |
| Stop-loss reference | $46.50 (prior analysis stop: $46.50) |
| Expiration | Dec 2026 (covers through Q4) |

**Note:** Buying 1 put for 48 shares means the contract protects slightly more shares than you own. At the HOLD signal level this is acceptable insurance — adjust to personal risk preference.

---

## Strategy 2: Accumulate (Alternative for HOLD signal in Low IV)

With low IV and a HOLD/buy-more signal context, an alternative is accumulating to ≥100 shares to enable a covered call on the full position — unlocking the INCOME strategy that aligns with DIVO's underlying CC methodology.

---

## Key Levels
| Level | Price | Significance |
|-------|-------|-------------|
| Stop-loss | $46.50 | Prior analysis stop |
| Put floor | $46.00 | Protective put strike |
| Current | $47.80 | Baseline |
| Resistance | $50.00 | Round-number resistance |

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── IAU: LONG + HOLD + Low-Moderate IV → Protective Put (<100 shares) ────────
REPORTS["IAU"] = f"""---
trade_report: true
schema_version: 1
ticker: IAU
company: iShares Gold Trust
report_type: OPTIONS
generated_at: {DATE}
signal: HOLD
price_at_analysis: 83.00
iv_rank: 40
strategy_outlook: HEDGE
recommended_strategy: Protective Put
position_bias: LONG
nearest_catalyst_date: 2026-09-17
run_id: {RUN_ID}
---

# Options Analysis: IAU — iShares Gold Trust

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$83.00 | **Gold proxy ETF**
**Your Position:** LONG ~16 shares (< 100 shares — collar unavailable; protective put recommended)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~16% | Gold ETF; low structural IV |
| IV Rank (52-week) | ~40% | Moderate — slightly below median |
| IV Percentile | ~38% | Reasonable put prices |
| 30-Day HV | ~13% | IV running at modest premium |
| IV/HV Ratio | ~1.23 | Options moderately rich vs realized vol |
| IV Skew | Mild | Puts slightly elevated; macro hedging demand |

**IV Environment: LOW-MODERATE**
**Strategy Bias: HEDGE (HOLD + moderate IV → collar; <100 shares → protective put)**

IAU (gold proxy) has a HOLD signal (composite 59/B) with strong +13.3% gain. With only ~16 shares, covered-call collars are unavailable. The protective put is appropriate to lock in gains and hedge against a gold pullback, particularly with Fed meeting catalysts on 2026-09-17.

---

## Strategy 1: Protective Put — RECOMMENDED

**Trade Details (indicative):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Protection | Buy | $80 (slightly OTM) | Dec 2026 | Put | ~$2.40 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Cost | ~$2.40 × 1 contract = ~$240 |
| Protection level | $80.00 floor |
| Premium as % of position | ~$240 / $1,328 ≈ 18% (somewhat elevated) |
| Consideration | May want to wait for IV to compress post-Sep 17 Fed meeting |

**Timing Note:** With a Fed catalyst on Sep 17, IV may spike and then crush. Consider waiting until after Sep 17 to buy puts at lower IV — if gold holds up.

---

## Key Levels
| Level | Price | Significance |
|-------|-------|-------------|
| Stop-loss | $79.00 | Prior analysis stop |
| Put floor | $80.00 | Protective put strike |
| Current | $83.00 | Baseline |
| All-time high | ~$85–$88 | Resistance zone |

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── O: LONG + HOLD + Moderate IV → Protective Put (<100 shares) ─────────────
REPORTS["O"] = f"""---
trade_report: true
schema_version: 1
ticker: O
company: Realty Income Corporation
report_type: OPTIONS
generated_at: {DATE}
signal: HOLD
price_at_analysis: 60.51
iv_rank: 45
strategy_outlook: HEDGE
recommended_strategy: Protective Put
position_bias: LONG
nearest_catalyst_date: 2026-10-28
run_id: {RUN_ID}
---

# Options Analysis: O — Realty Income Corporation

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$60.51 | **Dividend REIT — monthly payer**
**Next Earnings:** ~2026-10-28 (~43 days)
**Your Position:** LONG ~31 shares (< 100 shares — collar unavailable; protective put recommended)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~24% | REIT; moderate IV, rate-sensitive |
| IV Rank (52-week) | ~45% | Near median — moderate IV environment |
| IV Percentile | ~43% | Reasonably priced options |
| 30-Day HV | ~19% | IV at modest premium to realized |
| IV/HV Ratio | ~1.26 | Options moderately rich |
| IV Skew | Moderate | Puts elevated; interest-rate hedge demand |

**IV Environment: MODERATE**
**Strategy Bias: HEDGE (HOLD + moderate IV → collar lean; <100 shares → protective put)**

Realty Income (O) carries a HOLD signal (composite 58/B) with positive return (+11.3%). Rate-sensitivity and upcoming earnings (~Oct 28) make protective coverage prudent. With ~31 shares and moderate IV, a protective put provides affordable downside insurance through Q3 earnings.

---

## Strategy 1: Protective Put — RECOMMENDED

**Trade Details (indicative):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Protection | Buy | $58 (slightly OTM) | Nov 2026 | Put | ~$1.80 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Cost | ~$1.80 × 1 contract = ~$180 |
| Protection level | $58.00 floor |
| Premium as % of position | ~$180 / $1,876 ≈ 9.6% (reasonable) |
| Covers through | Nov 2026 earnings cycle |

**Dividend Note:** O pays monthly dividends (~$0.265/share). Your 31 shares generate ~$8.20/month. Over 2 months, dividends partially offset the put premium.

---

## Key Levels
| Level | Price | Significance |
|-------|-------|-------------|
| Stop-loss | $57.50 | Prior analysis stop |
| Put floor | $58.00 | Protective put strike |
| Current | $60.51 | Baseline |
| Resistance | $63–$65 | Prior high zone |

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── SCHF: LONG + HOLD + Low IV → Protective Put (<100 shares) ───────────────
REPORTS["SCHF"] = f"""---
trade_report: true
schema_version: 1
ticker: SCHF
company: Schwab International Equity ETF
report_type: OPTIONS
generated_at: {DATE}
signal: HOLD
price_at_analysis: 28.75
iv_rank: 30
strategy_outlook: HEDGE
recommended_strategy: Protective Put
position_bias: LONG
nearest_catalyst_date: 2026-09-17
run_id: {RUN_ID}
---

# Options Analysis: SCHF — Schwab International Equity ETF

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$28.75 | **International developed markets ETF**
**Next Catalyst:** ~2026-09-17 (Fed meeting macro impact)
**Your Position:** LONG ~26 shares (< 100 shares — collar unavailable; protective put recommended)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~17% | Broad international ETF; low structural IV |
| IV Rank (52-week) | ~30% | Below-median IV; protective puts are cheap |
| IV Percentile | ~28% | Favorable time to buy protection (low IV) |
| 30-Day HV | ~14% | IV at modest premium |
| IV/HV Ratio | ~1.21 | Options mildly rich |
| IV Skew | Low | Minimal skew; orderly market |

**IV Environment: LOW**
**Strategy Bias: HEDGE (HOLD + low IV → Collar; <100 shares → protective put)**

SCHF (international developed equity) has a HOLD signal (composite 67/B, from yesterday's run). With low IV rank ~30%, puts are inexpensive — a favorable time to buy protection. With ~26 shares and a HOLD signal, a protective put provides affordable downside insurance without limiting upside.

---

## Strategy 1: Protective Put — RECOMMENDED

**Trade Details (indicative):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Protection | Buy | $27 (slightly OTM) | Dec 2026 | Put | ~$0.90 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Cost | ~$0.90 × 1 contract = ~$90 |
| Protection level | $27.00 floor |
| Premium as % of position | ~$90 / $748 ≈ 12% (acceptable) |
| Why now | Low IV (rank 30%) makes protection cheap |

---

## Key Levels
| Level | Price | Significance |
|-------|-------|-------------|
| Stop-loss | $27.25 | Prior analysis stop |
| Put floor | $27.00 | Protective put strike |
| Current | $28.75 | Baseline |
| Resistance | $30.00 | Round-number target |

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── XIC: Canadian ETF — no US options ────────────────────────────────────────
REPORTS["XIC"] = f"""---
trade_report: true
schema_version: 1
ticker: XIC
company: iShares Core S&P/TSX Capped Composite Index ETF
report_type: OPTIONS
generated_at: {DATE}
signal: HOLD
price_at_analysis: 57.17
strategy_outlook: NEUTRAL
recommended_strategy: No Options Available (Canadian ETF)
position_bias: LONG
nearest_catalyst_date: 2026-09-17
run_id: {RUN_ID}
---

# Options Analysis: XIC — iShares Core S&P/TSX Capped Composite Index ETF

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$57.17 CAD | **Listed:** TSX (Canadian ETF)
**Your Position:** LONG ~9 units

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Options Availability

**XIC is a Canadian-listed ETF (Toronto Stock Exchange).** No standardized options chain available through US retail brokers.

**Options verdict: NOT AVAILABLE for standard retail options strategies.**

### Signal Context
- **Signal:** HOLD (composite 67/B)
- **Position:** LONG ~9 units
- **Recommendation:** No options overlay applicable. HOLD per signal.

### Alternatives
For Canadian broad market exposure with options:
- **XIU** (iShares S&P/TSX 60 ETF) may have limited options liquidity through Canadian brokers
- For macro hedging: EWC (iShares MSCI Canada ETF — US-listed) has liquid options

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ─── YNVDA: LONG + CAUTION + Moderate-High IV → Protective Put (<100 shares) ──
REPORTS["YNVDA"] = f"""---
trade_report: true
schema_version: 1
ticker: YNVDA
company: YieldMax NVDA Option Income Strategy ETF
report_type: OPTIONS
generated_at: {DATE}
signal: CAUTION
price_at_analysis: 12.50
iv_rank: 55
strategy_outlook: HEDGE
recommended_strategy: Protective Put
position_bias: LONG
nearest_catalyst_date: 2026-09-17
run_id: {RUN_ID}
---

# Options Analysis: YNVDA — YieldMax NVDA Option Income Strategy ETF

**Generated:** 2026-09-15 13:07 EDT
**Current Price:** ~$12.50 | **YieldMax covered-call income ETF on NVDA**
**Your Position:** LONG ~27 shares (< 100 shares — standard collar unavailable)

> **DISCLAIMER:** This is for educational and research purposes only. Not financial advice. Always do your own due diligence.

---

## Volatility Dashboard

### Implied Volatility Profile
| Metric | Value | Interpretation |
|--------|-------|----------------|
| 30-Day IV | ~58% | Elevated — inherits NVDA volatility via CC overlay |
| IV Rank (52-week) | ~55% | Moderate-high; NVDA volatility feeds through |
| IV Percentile | ~52% | Above-average IV environment |
| 30-Day HV | ~50% | IV running modest premium |
| IV/HV Ratio | ~1.16 | Options modestly expensive |
| NAV Decay Risk | HIGH | YieldMax ETFs sell NVDA upside to fund distributions; persistent NAV erosion |

**IV Environment: MODERATE-HIGH**
**Strategy Bias: HEDGE — CAUTION signal mandates downside protection**

YNVDA is a covered-call income ETF written on NVDA. It generates weekly distributions by selling NVDA call options, which limits upside and creates structural NAV decay over time (-18.5% to date). The CAUTION signal (composite 37/D) reflects the ongoing NAV erosion and the risk of accelerated downside if NVDA corrects. A protective put on YNVDA itself is appropriate to limit further capital destruction.

**⚠️ Liquidity Note:** YNVDA is a smaller YieldMax product. Verify options chain liquidity before trading — bid-ask spreads may be wide.

---

## Strategy 1: Protective Put — RECOMMENDED

**Trade Details (indicative — verify chain liquidity first):**
| Leg | Action | Strike | Expiration | Type | Est. Price |
|-----|--------|--------|------------|------|-----------|
| Protection | Buy | $11 (slightly OTM) | Nov 2026 | Put | ~$1.20 |

**Risk/Reward Profile:**
| Metric | Value |
|--------|-------|
| Cost | ~$1.20 × 1 contract = ~$120 |
| Protection level | $11.00 floor |
| Premium as % of position | ~$120 / $338 ≈ 35.5% (high; reflects elevated IV + small position) |
| Stop-loss reference | $11.75 (prior analysis stop) |

**⚠️ Cost-Benefit Check:** At $338 position value, $120 protection may not be economically rational. Consider whether exiting YNVDA and redeploying into NVDA equity directly (for full upside participation without CC drag) is preferable to continuing to hedge an eroding product.

---

## Alternative: Exit YNVDA

The CAUTION signal + NAV decay trajectory of YNVDA may make a clean exit the superior option over hedging. Redistributing the $338 to accumulate NVDA shares directly would eliminate the covered-call cap on upside.

---

## Key Levels
| Level | Price | Significance |
|-------|-------|-------------|
| Stop-loss | $11.75 | Prior analysis stop |
| Put floor | $11.00 | Protective put strike |
| Current | $12.50 | Baseline |
| NAV support | $10.00 | Approximate distribution-adjusted support |

---

*Generated by AI Trading Analyst — Options Strategy Engine*
*DISCLAIMER: Educational/research only. Not financial advice.*
"""

# ── WRITE ALL FILES ─────────────────────────────────────────────────────────────
tickers = ["CLOV","MARA","NIO","SPCE","ZAG","XEQT","IBIT","VDY","DIVO","IAU","O","SCHF","XIC","YNVDA"]

for ticker in tickers:
    filename = f"TRADE-OPTIONS-{ticker}-{TS}.md"
    with open(filename, "w") as f:
        f.write(REPORTS[ticker])
    print(f"✓ Wrote {filename}")

print("\nAll 14 options reports written.")
